# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  

jobs:
    save_hello_world_output:
      <<: *defaults

      steps:
        - run: echo "text to output here" > ~/output.txt

        - persist_to_workspace:
            root: ~/
            paths:
              - output.txt

    print_output_file:
      <<: *defaults

      steps:
        - attach_workspace:
            at: ~/
        - run: cat ~/output.txt
        - print_pipeline_id
            
workflows:
  # Name the workflow "welcome"
  myWorkFlow:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
